### ISSUE TITLE
最新版kcp-go write 死锁

### ISSUE THREAD

**Issue by dbskccc** [xtaci/kcp-go#112]
更新上当前git上最新版本的代码后出现，很多连接出现死锁在write上（kcp-go/sess.go:297）
出现此状况是可能此连接已经断了，但是服务端不知道，
请问下有什么办法让write不要死锁，因为客户端已经断线，无法再和后端通讯，但是后端只要write就死锁在kcp-go/sess.go:297了，然后整个程序都无法往下运行了
```
goroutine 33139 [select, 2632 minutes]:
github.com/xtaci/kcp-go.(*UDPSession).Write(0xc00094e000, 0xc0002b7800, 0x21, 0x400, 0x0, 0x0, 0x0)
	/home/yj/go/src/github.com/xtaci/kcp-go/sess.go:297 +0x523
_/mnt/ddd/bfdx/bf8000/server/bfkcp.(*TclientConn).Write(0xc00039c540, 0xc0002b7800, 0x21, 0x400, 0x0, 0x0)
	/mnt/ddd/bfdx/bf8000/server/bfkcp/kcpclientconn.go:442 +0x79
_/mnt/ddd/bfdx/bf8000/server/bfkcp.(*TclientConn).ProcessBc15.func2(0xf66e00, 0xc0003d6358, 0x1071f20, 0xc00039c540, 0xc000650000)
	/mnt/ddd/bfdx/bf8000/server/bfkcp/kcpclientconn.go:790 +0x1cd
sync.(*Map).Range(0xc00032e4d0, 0xc000125520)
	/usr/lib/go/src/sync/map.go:337 +0x38c
_/mnt/ddd/bfdx/bf8000/server/bfkcp.(*TclientConn).ProcessBc15(0xc0002c01c0, 0xc0006d70e0, 0xc0002b7800, 0x21, 0x400, 0x0, 0x0)
	/mnt/ddd/bfdx/bf8000/server/bfkcp/kcpclientconn.go:785 +0xfa8
_/mnt/ddd/bfdx/bf8000/server/bfkcp.processOneKcpConnection(0xc000312780)
	/mnt/ddd/bfdx/bf8000/server/bfkcp/bfkcp.go:249 +0x1fce
created by _/mnt/ddd/bfdx/bf8000/server/bfkcp.KcpServerMain
	/mnt/ddd/bfdx/bf8000/server/bfkcp/bfkcp.go:70 +0x7d3
```

**Comment by dbskccc** [comment]
有个SetWriteDeadline可以使用，先试下

**Comment by Nobup** [comment]
对端断开的情况write 应该是broken pip 才对。
