### ISSUE TITLE
test failures: too many open files (in fedora build roots)

### ISSUE THREAD

**Issue by decathorpe** [xtaci/kcp-go#40]
I'm trying to package this project for fedora, but I'm hitting a "too many open files" error during the mandatory execution of the test suite in the build root:

```
+ go test -compiler gc -ldflags '' github.com/xtaci/kcp-go
beginning tests, encryption:salsa20, fec:10/3
default mode result (4800ms):
avgrtt=1711 maxrtt=2779
normal mode result (2123ms):
avgrtt=131 maxrtt=281
fast mode result (2104ms):
avgrtt=133 maxrtt=264
panic: net.DialUDP: dial udp 127.0.0.1:9999: socket: too many open files
goroutine 1227 [running]:
github.com/xtaci/kcp-go.dialEcho(0x0, 0x0, 0x0)
	/builddir/build/BUILDROOT/golang-github-xtaci-kcp-go-3.15-1.fc27.x86_64/usr/share/gocode/src/github.com/xtaci/kcp-go/sess_test.go:47 +0x2d2
github.com/xtaci/kcp-go.parallel_client(0xc42019e650, 0xc420202f98, 0x477172)
	/builddir/build/BUILDROOT/golang-github-xtaci-kcp-go-3.15-1.fc27.x86_64/usr/share/gocode/src/github.com/xtaci/kcp-go/sess_test.go:348 +0x26
created by github.com/xtaci/kcp-go.TestParallel1024CLIENT_64BMSG_64CNT
	/builddir/build/BUILDROOT/golang-github-xtaci-kcp-go-3.15-1.fc27.x86_64/usr/share/gocode/src/github.com/xtaci/kcp-go/sess_test.go:342 +0x7e
FAIL	github.com/xtaci/kcp-go	12.556s
```

**Comment by xtaci** [comment]
try google "too many open files"

**Comment by decathorpe** [comment]
That's the first thing I did when encountering this problem -  so that comment isn't helpful. Fedora builds run as non-root user, so I can't run "ulimit -n" to change the file descriptor limit.

How many files is that test supposed to open, anyway? Because I've not ever run into a problem with to many open files in fedora builds before.

**Comment by xtaci** [comment]
at least 1024

**Comment by decathorpe** [comment]
Since I can't increase the open file limit to more than 1024, I'll disable that test. Thanks for your help.
