### ISSUE TITLE
test failure with go 1.9

### ISSUE THREAD

**Issue by decathorpe** [xtaci/kcp-go#50]
I'm not sure what the cause is here, but the tests fail with go 1.9.

The output from the failing test is:

```
+ go test -compiler gc -ldflags '' github.com/xtaci/kcp-go
beginning tests, encryption:salsa20, fec:10/3
panic: reflect: call of reflect.Value.Int on zero Value
goroutine 35 [running]:
reflect.Value.Int(0x0, 0x0, 0x0, 0x820250)
	/usr/lib/golang/src/reflect/value.go:908 +0x141
golang.org/x/net/internal/netreflect.socketOf(0xa162e0, 0xc4201ae000, 0x0, 0xc420033748, 0x743fce)
	/usr/share/gocode/src/golang.org/x/net/internal/netreflect/socket_posix.go:26 +0x196
golang.org/x/net/internal/netreflect.SocketOf(0xa162e0, 0xc4201ae000, 0x80e740, 0x1, 0xa162e0)
	/usr/share/gocode/src/golang.org/x/net/internal/netreflect/socket.go:23 +0x65
golang.org/x/net/ipv4.(*genericOpt).SetTOS(0xc420033778, 0xb8, 0xc4201ae000, 0xa162e0)
	/usr/share/gocode/src/golang.org/x/net/ipv4/genericopt_posix.go:33 +0x51
github.com/xtaci/kcp-go.(*Listener).SetDSCP(0xc420186080, 0x2e, 0x0, 0x0)
	/builddir/build/BUILDROOT/golang-github-xtaci-kcp-go-3.17-2.fc27.x86_64/usr/share/gocode/src/github.com/xtaci/kcp-go/sess.go:785 +0x8a
github.com/xtaci/kcp-go.sinkServer.func1(0xa130c0, 0xc420186080)
	/builddir/build/BUILDROOT/golang-github-xtaci-kcp-go-3.17-2.fc27.x86_64/usr/share/gocode/src/github.com/xtaci/kcp-go/sess_test.go:154 +0x7b
created by github.com/xtaci/kcp-go.sinkServer
	/builddir/build/BUILDROOT/golang-github-xtaci-kcp-go-3.17-2.fc27.x86_64/usr/share/gocode/src/github.com/xtaci/kcp-go/sess_test.go:150 +0x5c
FAIL	github.com/xtaci/kcp-go	0.018s
```

**Comment by gabstv** [comment]
I had the same issue, but it's not kcp-go's fault (well, maybe if the dep was vendored it would help).  
Run:
```go get -u golang.org/x/net/...```  
That should do it.

**Comment by decathorpe** [comment]
You're right, it was fixed by updating the `golang.org/x/net` packages. Thanks for pointing it out!
